services:
  ticket-booking-postgres:
    image: postgres:16-alpine
    container_name: ticket-booking-postgres
    environment:
      POSTGRES_DB: ticket_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - ./init-scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
