spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5435/ticket_booking
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/ticket-booking
